-- -----------------------------------------------------
-- Data for table `medlink`.`medicine`
-- -----------------------------------------------------
START TRANSACTION;
USE `medlink`;
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Risedronate', 1);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Alendronate',  1);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Ibandronate',  1);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Raloxifene',  1);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Infliximab',  1);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Adalimumab',  1);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Etanercept',  1);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Methtrexate',  1);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Hydroxychloroquine',  1);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Allopurinol',  1);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Colchicine',  1);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Amiodarone',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Digoxin',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Aspirin',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Aspirin/Dipyridamole',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Clopidogrel',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Prasugrel',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Ticagrelor',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Nitroglycerin',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Isosorbide mononitrate',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Ranolazine',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Hydrochlorthiazide',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Metolazone',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Furosemide',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Torsemide',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Bumetanide',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Spironolactone',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Nifedipine XL',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Amlodipine',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Amlodipine/benazepril',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Diltiazem',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Fenofibrate',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Genfibrozil',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Omega-3 Acid Ethyl Esters',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Niacin',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Ezetimibe',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Colesevelam',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Atenolol',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Metoprolol tartrate',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Metoprolol succinate',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Nebivolol',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Propranolol',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Carvedilol',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Lisinopril',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Lisinopril/hydrochlorthiazide',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Enalapril',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Pamipril',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Losartan',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Olmesartan',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Valsartan',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Dabigatran',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Rivaroxaban',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Apixaban',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Warfarin',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Enoxaparin',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Pravastatin',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Simvastatin',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Simvastatin/ezetimibe',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Atorvastatin',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Rosuvastatin',  2);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Adapalene',  3);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Isotretinoin',  3);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Rosiglitazone',  4);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Pioglitazone',  4);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Canagliflozin',  4);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Norgestimate/ethinyl estradiol',  4);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Drospirenone/ethinyl estradiol',  4);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Norethindrone',  4);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Norelgestromin/ethinyl estradiol',  4);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Etonogestrel/ethinyl estradiol',  4);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Insulin aspart',  4);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Insulin lispro',  4);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Insulin NPH',  4);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Insulin glargine',  4);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Insulin detemir',  4);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Exenatide',  4);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Prednisone',  4);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Methylprednisolone',  4);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Conjugated Estrogens',  4);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Testosterone',  4);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Levothyroxine',  4);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Anastrozole',  4);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Tamoxifen',  4);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Metformin',  4);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Sitagliptin',  4);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Glyburide',  4);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Glimepiride',  4);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Glipizide',  4);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Glyburide/metformin',  4);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Sitagliptin/metformin',  4);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Senna',  5);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Bisacodyl',  5);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Docusate',  5);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Senna/docusate',  5);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('PEG 3350',  5);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('PEG 3350 with electrolytes',  5);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Omeprazole',  5);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Esomeprazole',  5);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Pantoprazole',  5);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Lansoprazole',  5);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Dexlansoprazole',  5);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Famotidine',  5);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Ranitidine',  5);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Ondansetron',  5);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Prochlorperazine',  5);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Promethazine',  5);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Metoclopramide',  5);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Dicyclomine',  5);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Loperamide',  5);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Diphenoxylate/atropine',  5);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Mesalamine',  5);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Amoxicillin',  6);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Amoxicillin/clavulanate',  6);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Cephalexin',  6);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Cefuroxime',  6);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Cefdinir',  6);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Nitrofurantoin',  6);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Metronidazole',  6);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Sulfamethoxazole/trimethoprim',  6);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Clarithromycin',  6);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Azithromycin',  6);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Oseltamivir',  6);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Acyclovir',  6);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Valacyclovir',  6);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Ciprofloxacin',  6);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Levofloxacin',  6);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Moxifloxacin',  6);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Emtricitabine/tenofovir',  6);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Emtricitabine/tenofovir/efavirenz',  6);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Emtricitabine/tenofovir/rilpivirine',  6);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Emtricitabine/tenofovir/elvitegravir/cobicistat',  6);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Fluconazole',  6);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Itraconazole',  6);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Clindamycin',  6);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Doxycycline',  6);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Linezolid',  6);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Donepezil',  7);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Memantine',  7);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Meloxicam',  7);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Naproxen',  7);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Ibuprofen',  7);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Diclofenac',  7);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Celecoxib',  7);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Phenytoin',  7);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Valproic acid',  7);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Lamotrigine',  7);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Carbamazepine',  7);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Oxcarbazepine',  7);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Levetiracetam',  7);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Nicotine Patch',  7);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Varenicline',  7);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Sumatriptan',  7);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Eletriptan',  7);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Rizatriptan',  7);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Butalbital/acetaminophen/caffeine',  7);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Butalbital/aspirin/caffeine',  7);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Carisoprodol',  7);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Cyclobenzaprine',  7);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Morphine',  7);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Hydromorphone',  7);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Oxycodone',  7);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Oxycodone/APAP',  7);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Fentanyl',  7);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Hydrocodone/APAP',  7);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Buprenorphine/naloxone',  7);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Codeine/APAP',  7);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Tramadol',  7);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Gabapentin',  7);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Pregabalin',  7);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Lidocaine patch',  7);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Mometasone',  8);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Fluticasone',  8);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Diphenhydramine',  8);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Loratadine',  8);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Desloratadine',  8);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Fexofenadine',  8);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Olopatadine',  8);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Azelastine',  8);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Epinephrine',  8);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Cyclosporine (ophthalmic)',  8);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Timolol',  8);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Brimonidine',  8);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Brimonidine/timolol',  8);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Dorzolamide',  8);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Bimatoprost',  8);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Latanoprost',  8);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Travoprost',  8);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Hydrocodone/chlorpheniramine',  8);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Benzonatate',  8);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Guaifenesin',  8);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Dextromethorphan',  8);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Pseudoephedrine',  8);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Clonazepam',  9);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Lorazepam',  9);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Diazepam',  9);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Alprazolam',  9);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Amitriptyline',  9);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Nortriptyline',  9);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Trazodone',  9);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Mirtazapine',  9);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Bupropion',  9);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Fluoxetine',  9);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Sertraline',  9);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Paroxetine',  9);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Citalopram',  9);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Escitalopram',  9);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Zolpidem',  9);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Eszopiclone',  9);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Methylphenidate',  9);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Amphetamine/dextroamphetamine',  9);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Lisdexamfetamine',  9);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Atomoxetine',  9);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Modafinil',  9);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Venlafaxine',  9);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Desvenlafaxine',  9);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Duloxetine',  9);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Olanzapine',  9);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Quetiapine',  9);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Risperidone',  9);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Ziprasidone',  9);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Aripiprazole',  9);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Epoetin alfa',  10);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Darbepoetin',  10);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Cinacalcet',  10);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Sevelamer carbonate',  10);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Potassium chloride',  10);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Sildenafil',  11);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Vardenafil',  11);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Tadalafil',  11);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Tolterodine',  11);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Solifenacin',  11);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Darifenacin',  11);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Dutasteride',  11);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Finasteride',  11);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Terazosin',  11);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Doxazosin',  11);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Alfuzosin',  11);
INSERT INTO `medlink`.`medicine` (`medi_name`, `medi_category_id`) VALUES ('Tamsulosin',  11);

COMMIT;