-- -----------------------------------------------------
-- Data for table `medlink`.`medicine`
-- -----------------------------------------------------
START TRANSACTION;
USE `medlink`;
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (0, 'Risedronate', '', , 0);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (1, 'Alendronate', '', , 0);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (2, 'Ibandronate', '', , 0);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (3, 'Raloxifene', '', , 0);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (4, 'Infliximab', '', , 0);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (5, 'Adalimumab', '', , 0);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (6, 'Etanercept', '', , 0);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (7, 'Methtrexate', '', , 0);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (8, 'Hydroxychloroquine', '', , 0);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (9, 'Allopurinol', '', , 0);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (10, 'Colchicine', '', , 0);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (11, 'Amiodarone', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (12, 'Digoxin', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (13, 'Aspirin', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (14, 'Aspirin/Dipyridamole', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (15, 'Clopidogrel', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (16, 'Prasugrel', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (17, 'Ticagrelor', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (18, 'Nitroglycerin', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (19, 'Isosorbide mononitrate', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (20, 'Ranolazine', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (21, 'Hydrochlorthiazide', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (22, 'Metolazone', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (23, 'Furosemide', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (24, 'Torsemide', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (25, 'Bumetanide', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (26, 'Spironolactone', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (27, 'Nifedipine XL', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (28, 'Amlodipine', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (29, 'Amlodipine/benazepril', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (30, 'Diltiazem', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (31, 'Fenofibrate', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (32, 'Genfibrozil', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (33, 'Omega-3 Acid Ethyl Esters', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (34, 'Niacin', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (35, 'Ezetimibe', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (36, 'Colesevelam', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (37, 'Atenolol', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (38, 'Metoprolol tartrate', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (39, 'Metoprolol succinate', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (40, 'Nebivolol', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (41, 'Propranolol', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (42, 'Carvedilol', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (43, 'Lisinopril', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (44, 'Lisinopril/hydrochlorthiazide', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (45, 'Enalapril', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (46, 'Pamipril', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (47, 'Losartan', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (48, 'Olmesartan', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (49, 'Valsartan', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (50, 'Dabigatran', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (51, 'Rivaroxaban', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (52, 'Apixaban', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (53, 'Warfarin', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (54, 'Enoxaparin', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (55, 'Pravastatin', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (56, 'Simvastatin', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (57, 'Simvastatin/ezetimibe', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (58, 'Atorvastatin', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (59, 'Rosuvastatin', '', , 1);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (60, 'Adapalene', '', , 2);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (61, 'Isotretinoin', '', , 2);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (62, 'Rosiglitazone', '', , 3);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (63, 'Pioglitazone', '', , 3);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (64, 'Canagliflozin', '', , 3);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (65, 'Norgestimate/ethinyl estradiol', '', , 3);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (66, 'Drospirenone/ethinyl estradiol', '', , 3);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (67, 'Norethindrone', '', , 3);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (68, 'Norelgestromin/ethinyl estradiol', '', , 3);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (69, 'Etonogestrel/ethinyl estradiol', '', , 3);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (70, 'Insulin aspart', '', , 3);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (71, 'Insulin lispro', '', , 3);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (72, 'Insulin NPH', '', , 3);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (73, 'Insulin glargine', '', , 3);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (74, 'Insulin detemir', '', , 3);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (75, 'Exenatide', '', , 3);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (76, 'Prednisone', '', , 3);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (77, 'Methylprednisolone', '', , 3);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (78, 'Conjugated Estrogens', '', , 3);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (79, 'Testosterone', '', , 3);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (80, 'Levothyroxine', '', , 3);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (81, 'Anastrozole', '', , 3);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (82, 'Tamoxifen', '', , 3);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (83, 'Metformin', '', , 3);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (84, 'Sitagliptin', '', , 3);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (85, 'Glyburide', '', , 3);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (86, 'Glimepiride', '', , 3);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (87, 'Glipizide', '', , 3);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (88, 'Glyburide/metformin', '', , 3);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (89, 'Sitagliptin/metformin', '', , 3);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (90, 'Senna', '', , 4);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (91, 'Bisacodyl', '', , 4);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (92, 'Docusate', '', , 4);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (93, 'Senna/docusate', '', , 4);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (94, 'PEG 3350', '', , 4);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (95, 'PEG 3350 with electrolytes', '', , 4);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (96, 'Omeprazole', '', , 4);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (97, 'Esomeprazole', '', , 4);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (98, 'Pantoprazole', '', , 4);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (99, 'Lansoprazole', '', , 4);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (100, 'Dexlansoprazole', '', , 4);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (101, 'Famotidine', '', , 4);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (102, 'Ranitidine', '', , 4);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (103, 'Ondansetron', '', , 4);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (104, 'Prochlorperazine', '', , 4);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (105, 'Promethazine', '', , 4);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (106, 'Metoclopramide', '', , 4);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (107, 'Dicyclomine', '', , 4);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (108, 'Loperamide', '', , 4);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (109, 'Diphenoxylate/atropine', '', , 4);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (110, 'Mesalamine', '', , 4);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (111, 'Amoxicillin', '', , 5);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (112, 'Amoxicillin/clavulanate', '', , 5);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (113, 'Cephalexin', '', , 5);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (114, 'Cefuroxime', '', , 5);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (115, 'Cefdinir', '', , 5);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (116, 'Nitrofurantoin', '', , 5);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (117, 'Metronidazole', '', , 5);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (118, 'Sulfamethoxazole/trimethoprim', '', , 5);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (119, 'Clarithromycin', '', , 5);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (120, 'Azithromycin', '', , 5);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (121, 'Oseltamivir', '', , 5);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (122, 'Acyclovir', '', , 5);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (123, 'Valacyclovir', '', , 5);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (124, 'Ciprofloxacin', '', , 5);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (125, 'Levofloxacin', '', , 5);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (126, 'Moxifloxacin', '', , 5);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (127, 'Emtricitabine/tenofovir', '', , 5);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (128, 'Emtricitabine/tenofovir/efavirenz', '', , 5);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (129, 'Emtricitabine/tenofovir/rilpivirine', '', , 5);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (130, 'Emtricitabine/tenofovir/elvitegravir/cobicistat', '', , 5);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (131, 'Fluconazole', '', , 5);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (132, 'Itraconazole', '', , 5);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (133, 'Clindamycin', '', , 5);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (134, 'Doxycycline', '', , 5);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (135, 'Linezolid', '', , 5);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (136, 'Donepezil', '', , 6);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (137, 'Memantine', '', , 6);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (138, 'Meloxicam', '', , 6);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (139, 'Naproxen', '', , 6);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (140, 'Ibuprofen', '', , 6);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (141, 'Diclofenac', '', , 6);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (142, 'Celecoxib', '', , 6);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (143, 'Phenytoin', '', , 6);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (144, 'Valproic acid', '', , 6);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (145, 'Lamotrigine', '', , 6);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (146, 'Carbamazepine', '', , 6);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (147, 'Oxcarbazepine', '', , 6);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (148, 'Levetiracetam', '', , 6);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (149, 'Nicotine Patch', '', , 6);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (150, 'Varenicline', '', , 6);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (151, 'Sumatriptan', '', , 6);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (152, 'Eletriptan', '', , 6);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (153, 'Rizatriptan', '', , 6);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (154, 'Butalbital/acetaminophen/caffeine', '', , 6);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (155, 'Butalbital/aspirin/caffeine', '', , 6);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (156, 'Carisoprodol', '', , 6);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (157, 'Cyclobenzaprine', '', , 6);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (158, 'Morphine', '', , 6);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (159, 'Hydromorphone', '', , 6);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (160, 'Oxycodone', '', , 6);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (161, 'Oxycodone/APAP', '', , 6);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (162, 'Fentanyl', '', , 6);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (163, 'Hydrocodone/APAP', '', , 6);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (164, 'Buprenorphine/naloxone', '', , 6);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (165, 'Codeine/APAP', '', , 6);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (166, 'Tramadol', '', , 6);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (167, 'Gabapentin', '', , 6);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (168, 'Pregabalin', '', , 6);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (169, 'Lidocaine patch', '', , 6);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (170, 'Mometasone', '', , 7);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (171, 'Fluticasone', '', , 7);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (172, 'Diphenhydramine', '', , 7);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (173, 'Loratadine', '', , 7);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (174, 'Desloratadine', '', , 7);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (175, 'Fexofenadine', '', , 7);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (176, 'Olopatadine', '', , 7);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (177, 'Azelastine', '', , 7);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (178, 'Epinephrine', '', , 7);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (179, 'Cyclosporine (ophthalmic)', '', , 7);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (180, 'Timolol', '', , 7);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (181, 'Brimonidine', '', , 7);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (182, 'Brimonidine/timolol', '', , 7);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (183, 'Dorzolamide', '', , 7);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (184, 'Bimatoprost', '', , 7);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (185, 'Latanoprost', '', , 7);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (186, 'Travoprost', '', , 7);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (187, 'Hydrocodone/chlorpheniramine', '', , 7);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (188, 'Benzonatate', '', , 7);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (189, 'Guaifenesin', '', , 7);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (190, 'Dextromethorphan', '', , 7);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (191, 'Pseudoephedrine', '', , 7);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (192, 'Clonazepam', '', , 8);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (193, 'Lorazepam', '', , 8);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (194, 'Diazepam', '', , 8);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (195, 'Alprazolam', '', , 8);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (196, 'Amitriptyline', '', , 8);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (197, 'Nortriptyline', '', , 8);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (198, 'Trazodone', '', , 8);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (199, 'Mirtazapine', '', , 8);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (200, 'Bupropion', '', , 8);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (201, 'Fluoxetine', '', , 8);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (202, 'Sertraline', '', , 8);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (203, 'Paroxetine', '', , 8);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (204, 'Citalopram', '', , 8);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (205, 'Escitalopram', '', , 8);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (206, 'Zolpidem', '', , 8);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (207, 'Eszopiclone', '', , 8);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (208, 'Methylphenidate', '', , 8);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (209, 'Amphetamine/dextroamphetamine', '', , 8);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (210, 'Lisdexamfetamine', '', , 8);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (211, 'Atomoxetine', '', , 8);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (212, 'Modafinil', '', , 8);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (213, 'Venlafaxine', '', , 8);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (214, 'Desvenlafaxine', '', , 8);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (215, 'Duloxetine', '', , 8);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (216, 'Olanzapine', '', , 8);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (217, 'Quetiapine', '', , 8);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (218, 'Risperidone', '', , 8);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (219, 'Ziprasidone', '', , 8);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (220, 'Aripiprazole', '', , 8);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (221, 'Epoetin alfa', '', , 9);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (222, 'Darbepoetin', '', , 9);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (223, 'Cinacalcet', '', , 9);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (224, 'Sevelamer carbonate', '', , 9);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (225, 'Potassium chloride', '', , 9);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (226, 'Sildenafil', '', , 10);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (227, 'Vardenafil', '', , 10);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (228, 'Tadalafil', '', , 10);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (229, 'Tolterodine', '', , 10);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (230, 'Solifenacin', '', , 10);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (231, 'Darifenacin', '', , 10);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (232, 'Dutasteride', '', , 10);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (233, 'Finasteride', '', , 10);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (234, 'Terazosin', '', , 10);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (235, 'Doxazosin', '', , 10);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (236, 'Alfuzosin', '', , 10);
INSERT INTO `medlink`.`medicine` (`medi_id`, `medi_name`, `medi_description`, `medi_unit_of_measure`, `medi_category_id`) VALUES (237, 'Tamsulosin', '', , 10);

COMMIT;